version: '3.1'

services:
  node:
    build: '.'
    restart: always
    container_name: recording-admin
    extra_hosts:
      - "mongo-local:192.168.3.9"
    ports:
      - 80:3000
  mongo:
    image: mongo
    restart: always
    container_name: recording-mongo
    volumes:
      - mongo-db:/data/db
    ports:
      - 27017:27017
  resource-api:
    image: martin31/resource-api
    restart: always
    container_name: resourc-api
    extra_hosts:
      - "mongo-local:192.168.3.9"
    ports:
      - 3001:3001
  upload-server:
    image: martin31/upload-server
    restart: always
    container_name: upload-server
    extra_hosts:
      - "mongo-local:192.168.3.9"
    ports:
      - 8080:8080
      - 9001:9001
      - 9002:9002
  chat-server:
    image: martin31/chatserver
    restart: always
    container_name: chatserver
    ports:
      - 6503:6503
volumes:
  mongo-db:
