version: '3.1'

services:
  mongo:
    image: mongo
    # command: mongod --dbpath /Users/dachaofeng/data/db
    # restart: always
    container_name: recording-mongo
    volumes:
      - mongo-db:/Users/dachaofeng/data/db
    ports:
      - 27017:27017
  # web-server:
  #   image: 'martin31/recording-admin:1.2'
  #   restart: always
  #   container_name: recording-admin
  #   extra_hosts:
  #     - "mongo-local:${HOST}"
  #   ports:
  #     - 8000:3000
  resource-api:
    image: martin31/resource-api
    restart: always
    container_name: resource-api
    extra_hosts:
      - "mongo-local:${HOST}"
    ports:
      - 3001:3001
  upload-server:
    image: martin31/upload-server
    restart: always
    container_name: upload-server
    volumes:
      - upload-images:/usr/src/app/images/
    extra_hosts:
      - "mongo-local:${HOST}"
    ports:
      - 8080:8080
      - 9001:9001
      - 9002:9002
      - 9003:9003
      - 9004:9004
      - 9005:9005
      - 9006:9006
      - 9007:9007
      - 9008:9008
      - 9009:9009
      - 9010:9010
      - 9011:9011
      - 9012:9012
      - 6666:6666
  chat-server:
    image: martin31/chatserver
    restart: always
    container_name: chatserver
    ports:
      - 6503:6503
volumes:
  mongo-db:
  upload-images:
